
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes: 
      - .:/usr/app  # Diretório correto onde sua aplicação está localizada
    environment:
      - NODE_ENV=development  # Definindo a variável de ambiente para desenvolvimento
